# Generated by Django 5.2 on 2025-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='metodo_evaluacion',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('ESCRITO', 'Escrito teórico'), ('PRACTICO', 'Práctico'), ('TEORICO_PRACTICO', 'Teórico-Práctico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='metodologia',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
