# Generated by Django 5.2 on 2025-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_materia_metodo_evaluacion_materia_metodologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='metodo_evaluacion',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('ESCRITO', 'Escrito teórico'), ('PRACTICO', 'Práctico'), ('TEORICO_PRACTICO', 'Teórico-Práctico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='materia',
            name='metodologia',
            field=models.TextField(max_length=512),
        ),
    ]
